### ISSUE TITLE
Decide on a License for the project

### ISSUE THREAD

**Issue by hazel-ocean** [davidarmstronglewis/uap-rs#10]
Leaning towards Apache 2.0, possibly MIT.

Happy to hear anyone's thoughts that might be interested.

**Comment by blt** [comment]
Curious if this means the current version is not intended to be under [MIT](https://github.com/davidarmstronglewis/uap-rs/blob/3fc6592559ab51ec0e85d1fd5b085939493c94d7/Cargo.toml#L5)? IIRC most automatic license checkers will investigate `Cargo.toml`.

**Comment by hazel-ocean** [comment]
@blt Ah, forgot I had chosen a license already. I will honor that :)

**Comment by blt** [comment]
Much obliged. Thank you @davidarmstronglewis.
